// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/common/types/database';

const SUPABASE_URL = "https://hodedilnxwolnbrwfhbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZGVkaWxueHdvbG5icndmaGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTc2NTEsImV4cCI6MjA2Njg3MzY1MX0.urR_z4Ev84J8sV0puwml6ZEaSDeJ46z3k0utXPW_M0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});